services:
  - type: web
    name: oa-paper-scrapper-backend
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input
    startCommand: python manage.py migrate && gunicorn config.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: oa-paper-scrapper-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false

databases:
  - name: oa-paper-scrapper-db
    plan: free
    databaseName: oa_scrapper
    user: oa_user
