"""
ROB Comparison from to_json.py Export

This script loads the JSON export generated by to_json.py and performs cross-paper
ROB comparison on real scraped data.

Workflow:
  1. Run to_json.py with your DOI dataset to generate processed_export_*.json
  2. Run this script with the export JSON file
  3. Get a comprehensive ROB comparison report

Usage:
    python rob_comparison_from_export.py <path_to_export.json>

Example:
    python rob_comparison_from_export.py ../../../notebooks/exports/processed_export_1234567890.json

Output:
    - Formatted console report
    - rob_comparison_real_data_report.json (full report)
"""

import sys
import json
import os
from pathlib import Path
from rob_comparison import generate_comparison_report, export_comparison_report


def load_export_json(filepath):
    """Load the JSON export from to_json.py"""
    if not os.path.exists(filepath):
        print(f"❌ Error: File not found: {filepath}")
        return None
    
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)
        return data
    except json.JSONDecodeError as e:
        print(f"❌ Error: Invalid JSON file: {e}")
        return None
    except Exception as e:
        print(f"❌ Error reading file: {e}")
        return None


def extract_rob_artifacts_from_export(export_data):
    """
    Convert the to_json.py export format to rob_artifacts format.
    
    The export has: [{ paper_id, sections: [{heading, images, tables}], rob_artifacts?, ... }]
    We need: { paper_id, source, rob_artifacts: [...] }
    """
    if not export_data:
        return []
    
    papers_with_rob = []
    
    for entry in export_data:
        paper_id = entry.get('paper_id', 'unknown')
        source = entry.get('source', 'unknown')
        
        # Collect all ROB artifacts from the export
        rob_artifacts = entry.get('rob_artifacts', [])
        
        if rob_artifacts:
            papers_with_rob.append({
                'paper_id': paper_id,
                'source': source,
                'title': entry.get('title', 'Untitled'),
                'authors': entry.get('authors', []),
                'rob_artifacts': rob_artifacts,
            })
    
    return papers_with_rob


def print_report(report, num_papers):
    """Print a formatted ROB comparison report"""
    print("=" * 80)
    print("ROB COMPARISON REPORT - FROM REAL DATA")
    print("=" * 80)

    # Print summary
    print(f"\n📊 SUMMARY")
    print(f"  Total papers in export: {num_papers}")
    print(f"  Papers with ROB artifacts: {report['summary']['num_papers']}")
    print(f"  Total artifacts found: {report['summary']['total_artifacts']}")
    print(f"    - Text mentions: {report['summary']['total_text_artifacts']}")
    print(f"    - Table records: {report['summary']['total_table_artifacts']}")
    print(f"    - OCR results: {report['summary']['total_ocr_artifacts']}")

    # Print table alignment (if any tables found)
    if report['table_alignment']['domain_matrix']:
        print(f"\n📋 BIAS DOMAIN ALIGNMENT")
        print(f"  Domains found: {len(report['table_alignment']['domain_matrix'])}")
        for domain, papers_values in report['table_alignment']['domain_matrix'].items():
            print(f"\n  {domain.upper()}")
            for paper_id, value in papers_values.items():
                print(f"    {paper_id}: {value}")

        # Print consensus
        print(f"\n🎯 CONSENSUS (Majority Voting)")
        for domain, summary in report['table_alignment']['summary'].items():
            agreement = summary['agreement_rate']
            consensus = summary['consensus_value']
            print(f"  {domain}: {consensus} ({agreement:.0%} agreement)")

        # Print conflicts
        print(f"\n⚠️  CONFLICTS")
        if report['table_alignment']['conflicts']:
            for conflict in report['table_alignment']['conflicts']:
                domain = conflict['bias_domain']
                values = conflict['unique_values']
                papers = conflict['paper_ids_with_conflicts']
                print(f"  {domain}: {values} (in papers: {papers})")
        else:
            print("  No conflicts detected!")

    # Print popular sections
    if report['section_artifacts']['popular_sections']:
        print(f"\n📝 POPULAR ROB ASSESSMENT SECTIONS")
        for section, count in report['section_artifacts']['popular_sections'][:10]:
            print(f"  {section}: {count} paper(s)")

    # Print recommendations
    if report['recommendations']:
        print(f"\n💡 RECOMMENDATIONS ({len(report['recommendations'])} total)")
        for i, rec in enumerate(report['recommendations'], 1):
            print(f"  {i}. {rec['type']}")
            print(f"     {rec['message']}")
    else:
        print(f"\n💡 RECOMMENDATIONS")
        print(f"  No issues detected! All papers have consistent ROB assessments.")

    print("\n" + "=" * 80)


def main():
    # Get filepath from command line arguments
    if len(sys.argv) < 2:
        print("Usage: python rob_comparison_from_export.py <path_to_export.json>")
        print("\nExample:")
        print("  python rob_comparison_from_export.py ../../../notebooks/exports/processed_export_1234567890.json")
        print("\nSteps:")
        print("  1. Run to_json.py with your DOI dataset")
        print("  2. Find the generated processed_export_*.json file in notebooks/exports/")
        print("  3. Run this script with that file path")
        sys.exit(1)
    
    export_path = sys.argv[1]
    
    print(f"📂 Loading export file: {export_path}")
    
    # Load export data
    export_data = load_export_json(export_path)
    if not export_data:
        sys.exit(1)
    
    print(f"✅ Loaded {len(export_data)} papers from export")
    
    # Extract papers with ROB artifacts
    papers_with_rob = extract_rob_artifacts_from_export(export_data)
    print(f"✅ Found {len(papers_with_rob)} papers with ROB artifacts")
    
    if not papers_with_rob:
        print("\n⚠️  No ROB artifacts found in export. Make sure to_json.py ran ROB extraction.")
        print("   Try checking if the papers contain ROB-related content.")
        sys.exit(0)
    
    # Generate comparison report
    print("\n🔍 Generating cross-paper ROB comparison report...")
    report = generate_comparison_report(papers_with_rob)
    
    # Print formatted report
    print_report(report, len(export_data))
    
    # Export full report to JSON
    output_file = 'rob_comparison_real_data_report.json'
    export_comparison_report(papers_with_rob, output_file)
    print(f"✅ Full report exported to: {output_file}")


if __name__ == '__main__':
    main()
