# Generated by Django 5.2.13 on 2026-04-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
            ],
        ),
    ]
